//
// auto-generated by op2.py
//

// header
#include "op_lib_cpp.h"

// user kernel files
#include "init_grid_omp4kernel.cpp"
#include "set_ic_omp4kernel.cpp"
#include "neighbour_zero_omp4kernel.cpp"
#include "calc_dt_omp4kernel.cpp"
#include "get_neighbour_q_omp4kernel.cpp"
#include "get_bedge_q_omp4kernel.cpp"
#include "internal_fluxes_omp4kernel.cpp"
#include "euler_rhs_omp4kernel.cpp"
#include "set_workingQ_omp4kernel.cpp"
#include "update_Q_omp4kernel.cpp"
