//
// auto-generated by op2.py
//

void backwards_euler_update_Q_omp4_kernel(
  double *arg0,
  double *data1,
  int dat1size,
  double *data2,
  int dat2size,
  double *data3,
  int dat3size,
  double *data4,
  int dat4size,
  double *data5,
  int dat5size,
  double *data6,
  int dat6size,
  double *data7,
  int dat7size,
  double *data8,
  int dat8size,
  int count,
  int num_teams,
  int nthread){

  double arg0_l = *arg0;
  #pragma omp target teams num_teams(num_teams) thread_limit(nthread) map(to:data1[0:dat1size],data2[0:dat2size],data3[0:dat3size],data4[0:dat4size],data5[0:dat5size],data6[0:dat6size],data7[0:dat7size],data8[0:dat8size])
  #pragma omp distribute parallel for schedule(static,1)
  for ( int n_op=0; n_op<count; n_op++ ){
    //variable mapping
    const double *dt = &arg0_l;
    const double *q0 = &data1[15*n_op];
    const double *q1 = &data2[15*n_op];
    const double *q2 = &data3[15*n_op];
    const double *q3 = &data4[15*n_op];
    double *rhs0 = &data5[15*n_op];
    double *rhs1 = &data6[15*n_op];
    double *rhs2 = &data7[15*n_op];
    double *rhs3 = &data8[15*n_op];

    //inline function
    
    for(int i = 0; i < 15; i++) {
      rhs0[i] = q0[i] - (*dt) * rhs0[i];
      rhs1[i] = q1[i] - (*dt) * rhs1[i];
      rhs2[i] = q2[i] - (*dt) * rhs2[i];
      rhs3[i] = q3[i] - (*dt) * rhs3[i];
    }
    //end inline func
  }

  *arg0 = arg0_l;
}
