//
// auto-generated by op2.py
//

void get_bedge_q_omp4_kernel(
  int *data0,
  int dat0size,
  int *data1,
  int dat1size,
  int *map2,
  int map2size,
  double *data2,
  int dat2size,
  double *data3,
  int dat3size,
  double *data4,
  int dat4size,
  double *data5,
  int dat5size,
  int *col_reord,
  int set_size1,
  int start,
  int end,
  int num_teams,
  int nthread){

  #pragma omp target teams num_teams(num_teams) thread_limit(nthread) map(to:data0[0:dat0size],data1[0:dat1size]) \
    map(to: bc_r_ompkernel, bc_u_ompkernel, bc_v_ompkernel, bc_e_ompkernel, r_ompkernel[:15], FMASK_ompkernel[:15])\
    map(to:col_reord[0:set_size1],map2[0:map2size],data2[0:dat2size],data3[0:dat3size],data4[0:dat4size],data5[0:dat5size])
  #pragma omp distribute parallel for schedule(static,1)
  for ( int e=start; e<end; e++ ){
    int n_op = col_reord[e];
    int map2idx;
    map2idx = map2[n_op + set_size1 * 0];

    //variable mapping
    const int *bedge_type = &data0[1*n_op];
    const int *bedgeNum = &data1[1*n_op];
    const double *nx = &data2[15 * map2idx];
    const double *ny = &data3[15 * map2idx];
    const double *q = &data4[60 * map2idx];
    double *exteriorQ = &data5[60 * map2idx];

    //inline function
    
    int exInd = 0;
    int nInd = 0;
    if(*bedgeNum == 1) {
      exInd = 4 * 5;
      nInd = 5;
    } else if(*bedgeNum == 2) {
      exInd = 2 * 4 * 5;
      nInd = 2 * 5;
    }

    int *fmask;

    if(*bedgeNum == 0) {
      fmask = FMASK_ompkernel;
    } else if(*bedgeNum == 1) {
      fmask = &FMASK_ompkernel[5];
    } else {
      fmask = &FMASK_ompkernel[2 * 5];
    }

    if(*bedge_type == 0) {

      for(int i = 0; i < 5; i++) {
        exteriorQ[exInd + i * 4]     += bc_r_ompkernel;
        exteriorQ[exInd + i * 4 + 1] += bc_r_ompkernel * bc_u_ompkernel;
        exteriorQ[exInd + i * 4 + 2] +=  bc_r_ompkernel * bc_v_ompkernel;
        exteriorQ[exInd + i * 4 + 3] += bc_e_ompkernel;
      }
    } else if(*bedge_type == 1) {

      for(int i = 0; i < 5; i++) {
        int qInd = fmask[i] * 4;
        exteriorQ[exInd + i * 4]     += bc_r_ompkernel;
        exteriorQ[exInd + i * 4 + 1] += bc_r_ompkernel * bc_u_ompkernel;
        exteriorQ[exInd + i * 4 + 2] +=  bc_r_ompkernel * bc_v_ompkernel;
        exteriorQ[exInd + i * 4 + 3] += q[qInd + 3];
      }
    } else {

      for(int i = 0; i < 5; i++) {
        int qInd = fmask[i] * 4;
        exteriorQ[exInd + i * 4]     += q[qInd];
        exteriorQ[exInd + i * 4 + 1] += q[qInd + 1] - 2 * (nx[nInd + i] * q[qInd + 1] + ny[nInd + i] * q[qInd + 2]) * nx[nInd + i];
        exteriorQ[exInd + i * 4 + 2] += q[qInd + 2] - 2 * (nx[nInd + i] * q[qInd + 1] + ny[nInd + i] * q[qInd + 2]) * ny[nInd + i];


        exteriorQ[exInd + i * 4 + 3] += q[qInd + 3];
      }
    }
    //end inline func
  }

}
