//
// auto-generated by op2.py
//

// global constants
extern double gam;
extern double bc_mach;
extern double bc_alpha;
extern double bc_p;
extern double bc_r;
extern double bc_u;
extern double bc_v;
extern double bc_e;
extern double ones[15];
extern double r[15];
extern double s[15];
extern double Dr[225];
extern double Ds[225];
extern double Drw[225];
extern double Dsw[225];
extern int FMASK[15];
extern double LIFT[225];

// header
#include "op_lib_c.h"

void op_decl_const_char(int dim, char const *type,
int size, char *dat, char const *name){}
// user kernel files
#include "init_grid_acckernel.c"
#include "set_ic_acckernel.c"
#include "calc_dt_acckernel.c"
#include "set_workingQ_acckernel.c"
#include "update_Q_acckernel.c"
#include "get_neighbour_q_acckernel.c"
#include "get_bedge_q_acckernel.c"
#include "internal_fluxes_acckernel.c"
#include "euler_rhs_acckernel.c"
