//
// auto-generated by op2.py
//

//user function
#include "fluxes.h"

//user function
//#pragma acc routine
inline void euler_rhs_openacc( const double *q0, const double *q1, const double *q2,
                      const double *q3, double *exteriorQ0, double *exteriorQ1,
                      double *exteriorQ2, double *exteriorQ3, const double *rx,
                      const double *ry, const double *sx, const double *sy,
                      const double *fscale, const double *nx, const double *ny,
                      const double *dFdr0, const double *dFdr1,
                      const double *dFdr2, const double *dFdr3,
                      const double *dFds0, const double *dFds1,
                      const double *dFds2, const double *dFds3,
                      const double *dGdr0, const double *dGdr1,
                      const double *dGdr2, const double *dGdr3,
                      const double *dGds0, const double *dGds1,
                      const double *dGds2, const double *dGds3, double *flux0,
                      double *flux1, double *flux2, double *flux3,
                      double *qRHS0, double *qRHS1, double *qRHS2,
                      double *qRHS3) {

  for(int j = 0; j < 15; j++) {
    qRHS0[j] = (rx[j] * dFdr0[j] + sx[j] * dFds0[j]) + (ry[j] * dGdr0[j] + sy[j] * dGds0[j]);
  }

  for(int j = 0; j < 15; j++) {
    qRHS1[j] = (rx[j] * dFdr1[j] + sx[j] * dFds1[j]) + (ry[j] * dGdr1[j] + sy[j] * dGds1[j]);
  }

  for(int j = 0; j < 15; j++) {
    qRHS2[j] = (rx[j] * dFdr2[j] + sx[j] * dFds2[j]) + (ry[j] * dGdr2[j] + sy[j] * dGds2[j]);
  }

  for(int j = 0; j < 15; j++) {
    qRHS3[j] = (rx[j] * dFdr3[j] + sx[j] * dFds3[j]) + (ry[j] * dGdr3[j] + sy[j] * dGds3[j]);
  }


  roe(flux0, flux1, flux2, flux3, nx, ny, fscale, q0, q1, q2, q3, exteriorQ0,
      exteriorQ1, exteriorQ2, exteriorQ3);

  for(int i = 0; i < 3 * 5; i++) {
    exteriorQ0[i] = 0.0;
    exteriorQ1[i] = 0.0;
    exteriorQ2[i] = 0.0;
    exteriorQ3[i] = 0.0;
  }
}

// host stub function
void op_par_loop_euler_rhs(char const *name, op_set set,
  op_arg arg0,
  op_arg arg1,
  op_arg arg2,
  op_arg arg3,
  op_arg arg4,
  op_arg arg5,
  op_arg arg6,
  op_arg arg7,
  op_arg arg8,
  op_arg arg9,
  op_arg arg10,
  op_arg arg11,
  op_arg arg12,
  op_arg arg13,
  op_arg arg14,
  op_arg arg15,
  op_arg arg16,
  op_arg arg17,
  op_arg arg18,
  op_arg arg19,
  op_arg arg20,
  op_arg arg21,
  op_arg arg22,
  op_arg arg23,
  op_arg arg24,
  op_arg arg25,
  op_arg arg26,
  op_arg arg27,
  op_arg arg28,
  op_arg arg29,
  op_arg arg30,
  op_arg arg31,
  op_arg arg32,
  op_arg arg33,
  op_arg arg34,
  op_arg arg35,
  op_arg arg36,
  op_arg arg37,
  op_arg arg38){

  int nargs = 39;
  op_arg args[39];

  args[0] = arg0;
  args[1] = arg1;
  args[2] = arg2;
  args[3] = arg3;
  args[4] = arg4;
  args[5] = arg5;
  args[6] = arg6;
  args[7] = arg7;
  args[8] = arg8;
  args[9] = arg9;
  args[10] = arg10;
  args[11] = arg11;
  args[12] = arg12;
  args[13] = arg13;
  args[14] = arg14;
  args[15] = arg15;
  args[16] = arg16;
  args[17] = arg17;
  args[18] = arg18;
  args[19] = arg19;
  args[20] = arg20;
  args[21] = arg21;
  args[22] = arg22;
  args[23] = arg23;
  args[24] = arg24;
  args[25] = arg25;
  args[26] = arg26;
  args[27] = arg27;
  args[28] = arg28;
  args[29] = arg29;
  args[30] = arg30;
  args[31] = arg31;
  args[32] = arg32;
  args[33] = arg33;
  args[34] = arg34;
  args[35] = arg35;
  args[36] = arg36;
  args[37] = arg37;
  args[38] = arg38;

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(6);
  op_timers_core(&cpu_t1, &wall_t1);
  OP_kernels[6].name      = name;
  OP_kernels[6].count    += 1;


  if (OP_diags>2) {
    printf(" kernel routine w/o indirection:  euler_rhs");
  }

  int set_size = op_mpi_halo_exchanges_cuda(set, nargs, args);


  if (set_size >0) {


    //Set up typed device pointers for OpenACC

    double* data0 = (double*)arg0.data_d;
    double* data1 = (double*)arg1.data_d;
    double* data2 = (double*)arg2.data_d;
    double* data3 = (double*)arg3.data_d;
    double* data4 = (double*)arg4.data_d;
    double* data5 = (double*)arg5.data_d;
    double* data6 = (double*)arg6.data_d;
    double* data7 = (double*)arg7.data_d;
    double* data8 = (double*)arg8.data_d;
    double* data9 = (double*)arg9.data_d;
    double* data10 = (double*)arg10.data_d;
    double* data11 = (double*)arg11.data_d;
    double* data12 = (double*)arg12.data_d;
    double* data13 = (double*)arg13.data_d;
    double* data14 = (double*)arg14.data_d;
    double* data15 = (double*)arg15.data_d;
    double* data16 = (double*)arg16.data_d;
    double* data17 = (double*)arg17.data_d;
    double* data18 = (double*)arg18.data_d;
    double* data19 = (double*)arg19.data_d;
    double* data20 = (double*)arg20.data_d;
    double* data21 = (double*)arg21.data_d;
    double* data22 = (double*)arg22.data_d;
    double* data23 = (double*)arg23.data_d;
    double* data24 = (double*)arg24.data_d;
    double* data25 = (double*)arg25.data_d;
    double* data26 = (double*)arg26.data_d;
    double* data27 = (double*)arg27.data_d;
    double* data28 = (double*)arg28.data_d;
    double* data29 = (double*)arg29.data_d;
    double* data30 = (double*)arg30.data_d;
    double* data31 = (double*)arg31.data_d;
    double* data32 = (double*)arg32.data_d;
    double* data33 = (double*)arg33.data_d;
    double* data34 = (double*)arg34.data_d;
    double* data35 = (double*)arg35.data_d;
    double* data36 = (double*)arg36.data_d;
    double* data37 = (double*)arg37.data_d;
    double* data38 = (double*)arg38.data_d;
    #pragma acc parallel loop independent deviceptr(data0,data1,data2,data3,data4,data5,data6,data7,data8,data9,data10,data11,data12,data13,data14,data15,data16,data17,data18,data19,data20,data21,data22,data23,data24,data25,data26,data27,data28,data29,data30,data31,data32,data33,data34,data35,data36,data37,data38)
    for ( int n=0; n<set->size; n++ ){
      euler_rhs_openacc(
        &data0[15*n],
        &data1[15*n],
        &data2[15*n],
        &data3[15*n],
        &data4[15*n],
        &data5[15*n],
        &data6[15*n],
        &data7[15*n],
        &data8[15*n],
        &data9[15*n],
        &data10[15*n],
        &data11[15*n],
        &data12[15*n],
        &data13[15*n],
        &data14[15*n],
        &data15[15*n],
        &data16[15*n],
        &data17[15*n],
        &data18[15*n],
        &data19[15*n],
        &data20[15*n],
        &data21[15*n],
        &data22[15*n],
        &data23[15*n],
        &data24[15*n],
        &data25[15*n],
        &data26[15*n],
        &data27[15*n],
        &data28[15*n],
        &data29[15*n],
        &data30[15*n],
        &data31[15*n],
        &data32[15*n],
        &data33[15*n],
        &data34[15*n],
        &data35[15*n],
        &data36[15*n],
        &data37[15*n],
        &data38[15*n]);
    }
  }

  // combine reduction data
  op_mpi_set_dirtybit_cuda(nargs, args);

  // update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[6].time     += wall_t2 - wall_t1;
  OP_kernels[6].transfer += (float)set->size * arg0.size;
  OP_kernels[6].transfer += (float)set->size * arg1.size;
  OP_kernels[6].transfer += (float)set->size * arg2.size;
  OP_kernels[6].transfer += (float)set->size * arg3.size;
  OP_kernels[6].transfer += (float)set->size * arg4.size * 2.0f;
  OP_kernels[6].transfer += (float)set->size * arg5.size * 2.0f;
  OP_kernels[6].transfer += (float)set->size * arg6.size * 2.0f;
  OP_kernels[6].transfer += (float)set->size * arg7.size * 2.0f;
  OP_kernels[6].transfer += (float)set->size * arg8.size;
  OP_kernels[6].transfer += (float)set->size * arg9.size;
  OP_kernels[6].transfer += (float)set->size * arg10.size;
  OP_kernels[6].transfer += (float)set->size * arg11.size;
  OP_kernels[6].transfer += (float)set->size * arg12.size;
  OP_kernels[6].transfer += (float)set->size * arg13.size;
  OP_kernels[6].transfer += (float)set->size * arg14.size;
  OP_kernels[6].transfer += (float)set->size * arg15.size;
  OP_kernels[6].transfer += (float)set->size * arg16.size;
  OP_kernels[6].transfer += (float)set->size * arg17.size;
  OP_kernels[6].transfer += (float)set->size * arg18.size;
  OP_kernels[6].transfer += (float)set->size * arg19.size;
  OP_kernels[6].transfer += (float)set->size * arg20.size;
  OP_kernels[6].transfer += (float)set->size * arg21.size;
  OP_kernels[6].transfer += (float)set->size * arg22.size;
  OP_kernels[6].transfer += (float)set->size * arg23.size;
  OP_kernels[6].transfer += (float)set->size * arg24.size;
  OP_kernels[6].transfer += (float)set->size * arg25.size;
  OP_kernels[6].transfer += (float)set->size * arg26.size;
  OP_kernels[6].transfer += (float)set->size * arg27.size;
  OP_kernels[6].transfer += (float)set->size * arg28.size;
  OP_kernels[6].transfer += (float)set->size * arg29.size;
  OP_kernels[6].transfer += (float)set->size * arg30.size;
  OP_kernels[6].transfer += (float)set->size * arg31.size * 2.0f;
  OP_kernels[6].transfer += (float)set->size * arg32.size * 2.0f;
  OP_kernels[6].transfer += (float)set->size * arg33.size * 2.0f;
  OP_kernels[6].transfer += (float)set->size * arg34.size * 2.0f;
  OP_kernels[6].transfer += (float)set->size * arg35.size * 2.0f;
  OP_kernels[6].transfer += (float)set->size * arg36.size * 2.0f;
  OP_kernels[6].transfer += (float)set->size * arg37.size * 2.0f;
  OP_kernels[6].transfer += (float)set->size * arg38.size * 2.0f;
}
