//
// auto-generated by op2.py
//

// global constants
extern double gam;
extern double bc_mach;
extern double bc_alpha;
extern double bc_p;
extern double bc_r;
extern double bc_u;
extern double bc_v;
extern double bc_e;
extern double ones[15];
extern double r[15];
extern double s[15];
extern double Dr[225];
extern double Ds[225];
extern double Drw[225];
extern double Dsw[225];
extern int FMASK[15];
extern double LIFT[225];

// header
#include "op_lib_cpp.h"

// user kernel files
#include "init_grid_seqkernel.cpp"
#include "set_ic_seqkernel.cpp"
#include "neighbour_zero_seqkernel.cpp"
#include "calc_dt_seqkernel.cpp"
#include "get_neighbour_q_seqkernel.cpp"
#include "get_bedge_q_seqkernel.cpp"
#include "internal_fluxes_seqkernel.cpp"
#include "euler_rhs_seqkernel.cpp"
#include "set_workingQ_seqkernel.cpp"
#include "update_Q_seqkernel.cpp"
